### ISSUE TITLE
Javalina SEO Audit fixes

### ISSUE THREAD

**Issue by chrismkim** [erinmgriffith/Active-projects#75]
- [x] change logo alt text to "Javalina Coffee House"
- [x] sitemap xml
- [x] robots.txt
- [x] fixed www and non-www versions
- [x] HTTP/HTTPS issue, set one as priority
- [x] Broken links, news, newmexico.aaa.com, and sunset magazine
- [x] Many empty alt text on images
- [x] Duplicate page titles
- [x] too long meta descriptions, keep under 160 char

**Comment by erinmgriffith** [comment]
re: robots.txt- from what I rea robot.txt is only there to block spiders from indexing. They index automatically and we want google to index. Confused as to if or what I am to do with this.

**Comment by erinmgriffith** [comment]
re: www and non-www, I am not sure, but I think that we already have this. When I looked up most recommended having non-www forward to www. When I type javalinacoffeehouse.com without www it forwards automatically to www. Is this right? I have no idea really what this means or how to enact it if it is not. Will continue researching.

**Comment by chrismkim** [comment]
I dont know if that is right or not. It doesnt say much more than that. Bots penalize duplicate sites and it says to set one as primary in the .htaccess file

**Comment by chrismkim** [comment]
for robots.txt it just expects to find one, so at least just put the two lines it expects

User-Agent: *
Disallow: /
more info is here if interested

http://neilpatel.com/blog/robots-txt/

**Comment by erinmgriffith** [comment]
did all but www and https- 
am still confused about https- may need to call godaddy. Need SSL to be https. I believe the SSL I had purchased covers multiple sites and subdomains, but javalina not showing up as https. do not know where to set as priority. may have to call godaddy support.

www-the .htaccess file is something that is created by apache when a site is running on an apache web server. I don't believe our are and there is no htaccess I can find. I think it must be ok because redirects automatically anyway.

**Comment by chrismkim** [comment]
Ok. Good work kimo sabe. Let me know when you make your changes live so i can rerun audit to look what it says.

**Comment by chrismkim** [comment]
I fixed the last two issues via search console, which is why it confused you, its settings for that specifically in google search console.

closing now. good work.
