### ISSUE TITLE
Proofread copy

### ISSUE THREAD

**Issue by erinmgriffith** [erinmgriffith/Active-projects#90]
Proofread text and send to linda to review

**Comment by chrismkim** [comment]
Wrong/incomplete text in the "Our Approach Section"
About us - comma after development - a space after the period before Operating
erin section - capitalize C in college - a space after the comma after non-templated
chris section - should be stop-overs - doesn't not doesnt
the text under the bella and barkus section should line up properly
the kitty picture slot is misaligned

**Comment by chrismkim** [comment]
portfolio

web section
- take the "a" away from the sentence with "primarily" on the polished plum section

**Comment by chrismkim** [comment]
services section

web - doesnt say anything except We are a small husband and wife team located in t"

web, marketing, and other all say this actually.

**Comment by chrismkim** [comment]
envision,

take out this "

Design should be personal. Every business is the product of someone's dream and vision. We want to create experiences that reflect the style and vision of each client a unique and personal way."

**Comment by chrismkim** [comment]
SERvices section

marketing 
there should be a "to" in this sentence 

"Want to handle most things yourself and use us to give recommendations, implement a few tools, generate reports, or just bounce ideas off of?"

after "or" and before "just"

one paragraph starts "hough" instead of "though"

a space needs to be after the second to last comma

Other Services

too many periods after first sentence

2nd and 3rd lines need capitalization after the ?

capitalization on most of the 4th section. the "or"
